BUOY_BACKUP_DIST = 2.0
BUOY_BACKUP_FOR_OVER_DIST = 0.2
BUOY_OVER_DEPTH = 0.4
BUOY_SEARCH_DEPTH = 0.5
BUOY_TO_PIPE_DIST = 2.5

PIPE_SEARCH_DEPTH = 0.2
PIPE_FOLLOW_DEPTH = 0.5

BINS_CAM_TO_ARM_OFFSET = 0.12
BINS_HEIGHT = 0.5
BINS_DROP_ALTITUDE = BINS_HEIGHT + 0.65
BINS_PICKUP_ALTITUDE = BINS_HEIGHT + 0.2
BINS_SEARCH_DEPTH = 0.5

HYDROPHONES_SEARCH_DEPTH = 0.5
